FROM python:3.12-slim-bullseye

USER root

# Install Java 17 (available in bullseye-backports) + dependencies
RUN apt-get update && \
    apt-get install -y apt-transport-https gnupg wget libgomp1 tzdata procps && \
    mkdir -p /etc/apt/keyrings && \
    wget -qO - https://packages.adoptium.net/artifactory/api/gpg/key/public | tee /etc/apt/keyrings/adoptium.asc && \
    echo "deb [signed-by=/etc/apt/keyrings/adoptium.asc] https://packages.adoptium.net/artifactory/deb $(. /etc/os-release && echo $VERSION_CODENAME) main" | tee /etc/apt/sources.list.d/adoptium.list && \
    apt-get update && \
    apt-get install -y temurin-17-jre && \
    ln -snf /usr/share/zoneinfo/Etc/GMT-1 /etc/localtime && \
    echo "Etc/GMT-1" > /etc/timezone && \
    apt-get clean

# Install Spark 3.4.3
RUN wget -q https://archive.apache.org/dist/spark/spark-3.4.3/spark-3.4.3-bin-hadoop3.tgz && \
    tar -xzf spark-3.4.3-bin-hadoop3.tgz -C /opt/ && \
    mv /opt/spark-3.4.3-bin-hadoop3 /opt/spark && \
    rm spark-3.4.3-bin-hadoop3.tgz

ENV SPARK_HOME=/opt/spark
ENV PATH=$SPARK_HOME/bin:$SPARK_HOME/sbin:$PATH
ENV JAVA_HOME=/usr/lib/jvm/temurin-17-jre-amd64
ENV PYSPARK_PYTHON=python3
ENV PYSPARK_DRIVER_PYTHON=python3
ENV TZ=Etc/GMT-1

RUN pip install numpy==1.26.4 scikit-learn==1.5.2 lightgbm==4.5.0
RUN pip install mlflow prometheus_client joblib pandas pyspark==3.4.3

# Create spark user
RUN useradd -m -s /bin/bash spark
USER spark
