apiVersion: 1
datasources:
  - name: MySQL
    uid: mysql-ds
    type: mysql
    url: mysql:3306
    database: $MYSQL_DATABASE
    user: $MYSQL_USER
    secureJsonData:
      password: "$MYSQL_PASSWORD"
    access: proxy
    isDefault: true
  - name: Prometheus
    uid: prometheus-ds
    type: prometheus
    url: http://prometheus:9090
    access: proxy
